@extends('layouts.private-finance')
@section('title', 'تفاصيل الموظف')
@section('privacy-notice', 'صفحة موظف خاصة للقراءة فقط. الصلاحيات الظاهرة محسوبة مباشرة من الأدوار الحالية ولا تمنح أي وصول جديد.')
@section('content')
<div class="staff-detail rtl">
  <p><a href="{{ route('admin.staff.index') }}">العودة إلى دليل الموظفين</a></p>
  <section><h2>الحساب</h2><dl><dt>الاسم</dt><dd>{{ $employee->name }}</dd><dt>رقم الموظف</dt><dd dir="ltr">{{ $employee->employee_number }}</dd><dt>المسمى الوظيفي</dt><dd>{{ $employee->job_title ?: 'غير محدد' }}</dd><dt>القسم</dt><dd>{{ $employee->staffDepartment?->name ?? 'غير محدد' }}</dd><dt>البريد</dt><dd dir="ltr">{{ $employee->email }}</dd><dt>حالة الحساب</dt><dd>{{ $employee->account_status->label() }}</dd><dt>أنشأ حساب الموظف</dt><dd>{{ $staffCreator?->actor?->name ?? 'حساب سابق/غير مسجل' }}</dd><dt>آخر تغيير للحالة</dt><dd>{{ $employee->account_status_changed_at?->format('Y-m-d H:i:s') ?? 'لم تتغير' }} @if($employee->account_status_changed_at) UTC @endif</dd><dt>تاريخ الانضمام</dt><dd>{{ $employee->created_at?->format('Y-m-d H:i') }}</dd></dl></section>
  <section><h2>الأدوار الحالية</h2><div class="chips">@foreach($employee->roles as $role)<span>{{ $role->name }}</span>@endforeach</div></section>
  @if($employee->account_status !== \App\Enums\AccountStatus::Terminated)
  <section><h2>الهوية الوظيفية</h2><p>رقم الموظف ثابت ولا يتغير. القسم ينظم الموظفين ولا يمنح صلاحيات.</p><form method="POST" action="{{ route('admin.staff.profile.update', $employee) }}">@csrf @method('PATCH')<label>الاسم الكامل<input name="name" value="{{ $employee->name }}" minlength="2" maxlength="120" required></label><label>الهاتف<input name="phone" value="{{ $employee->phone }}" maxlength="30" dir="ltr"></label><label>المسمى الوظيفي<input name="job_title" value="{{ $employee->job_title }}" maxlength="120"></label><label>القسم<select name="staff_department_id"><option value="">بدون قسم</option>@foreach($availableDepartments as $department)<option value="{{ $department->id }}" @selected($employee->staff_department_id === $department->id)>{{ $department->name }}</option>@endforeach</select></label><label>سبب التغيير<textarea name="reason" minlength="5" maxlength="500" required>{{ old('reason') }}</textarea></label><label>كلمة مرور حسابك<input type="password" name="current_password" autocomplete="current-password" required></label><button>حفظ الهوية الوظيفية</button></form></section>
  @endif
  @if($employee->id !== auth()->id() && $employee->account_status !== \App\Enums\AccountStatus::Terminated)
  <section><h2>تغيير بريد الموظف</h2><p>إجراء أمني: ينهي الجلسات، يبطل روابط الاستعادة والدعوة السابقة، ويدوّر رمز تذكر الدخول.</p><form method="POST" action="{{ route('admin.staff.email.update', $employee) }}">@csrf @method('PATCH')<label>البريد الجديد<input type="email" name="email" value="{{ $employee->email }}" maxlength="191" autocomplete="off" required></label><label>سبب التغيير<textarea name="reason" minlength="5" maxlength="500" required></textarea></label><label>كلمة مرور حسابك<input type="password" name="current_password" autocomplete="current-password" required></label><button>تغيير البريد وقطع الجلسات</button></form></section>
  @endif
  @if($employee->account_status !== \App\Enums\AccountStatus::Terminated)
  <section><h2>نطاق المواقع وجدول الدوام</h2><p>المواقع تحدد نطاق التكليف المستقبلي ولا تمنح صلاحية بحد ذاتها. الأوقات حسب المنطقة المحددة.</p><form method="POST" action="{{ route('admin.staff.scope-schedule.update', $employee) }}">@csrf @method('PATCH')
    <fieldset><legend>المواقع المسندة</legend>@forelse($availableLocations as $location)<label><input type="checkbox" name="location_ids[]" value="{{ $location->id }}" @checked($employee->staffLocations->contains('id', $location->id))> {{ $location->name }}</label>@empty<p>لا توجد مواقع نشطة.</p>@endforelse</fieldset>
    <label>المنطقة الزمنية<input name="timezone" value="{{ $scheduleTimezone }}" list="staff-timezones" maxlength="64" required><datalist id="staff-timezones"><option value="Asia/Hebron"><option value="UTC"></datalist></label>
    @php($dayLabels = ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'])
    <div class="schedule-grid">@foreach($dayLabels as $dayNumber => $dayLabel) @php($day = $workSchedule->get($dayNumber))<fieldset><legend>{{ $dayLabel }}</legend><input type="hidden" name="schedule[{{ $dayNumber }}][day_of_week]" value="{{ $dayNumber }}"><input type="hidden" name="schedule[{{ $dayNumber }}][is_working]" value="0"><label><input type="checkbox" name="schedule[{{ $dayNumber }}][is_working]" value="1" @checked($day?->is_working)> يوم عمل</label><label>من<input type="time" name="schedule[{{ $dayNumber }}][starts_at]" value="{{ $day?->starts_at ? substr($day->starts_at, 0, 5) : '' }}"></label><label>إلى<input type="time" name="schedule[{{ $dayNumber }}][ends_at]" value="{{ $day?->ends_at ? substr($day->ends_at, 0, 5) : '' }}"></label></fieldset>@endforeach</div>
    <label>سبب التغيير<textarea name="reason" minlength="5" maxlength="500" required></textarea></label><label>كلمة مرور حسابك<input type="password" name="current_password" autocomplete="current-password" required></label><button>حفظ النطاق والدوام</button>
  </form></section>
  @endif
  <section><h2>ملخص الأمان</h2><dl><dt>المصادقة الثنائية (2FA)</dt><dd>غير متاحة بعد</dd><dt>آخر تغيير لكلمة المرور</dt><dd>{{ $employee->password_changed_at?->format('Y-m-d H:i:s') ?? 'غير مسجل' }} @if($employee->password_changed_at) UTC @endif</dd><dt>آخر تسجيل دخول</dt><dd>{{ $employee->last_login_at?->format('Y-m-d H:i:s') ?? 'لم يسجل الدخول' }} @if($employee->last_login_at) UTC @endif</dd><dt>عدد مرات الدخول</dt><dd>{{ $employee->login_count }}</dd><dt>محاولات فاشلة منذ آخر دخول ناجح</dt><dd>{{ $employee->failed_login_count }}</dd><dt>آخر محاولة فاشلة</dt><dd>{{ $employee->last_failed_login_at?->format('Y-m-d H:i:s') ?? 'لا توجد' }} @if($employee->last_failed_login_at) UTC @endif</dd><dt>الجلسات النشطة</dt><dd>{{ $sessionSummary['active_count'] ?? 'غير متاح' }}</dd><dt>آخر نشاط</dt><dd>{{ $sessionSummary['last_active_at']?->format('Y-m-d H:i:s') ?? 'لا يوجد' }} @if($sessionSummary['last_active_at']) UTC @endif</dd><dt>عمليات التوصيل النشطة</dt><dd>{{ $activeDeliveryCount }}</dd></dl><p>لا تعرض هذه الصفحة عنوان IP أو بيانات الجهاز أو محتوى الجلسة.</p></section>
  <section><h2>عبء المهام</h2><dl><dt>مهام نشطة</dt><dd>{{ $taskWorkload['active'] }}</dd><dt>متأخرة</dt><dd>{{ $taskWorkload['overdue'] }}</dd><dt>مكتملة اليوم</dt><dd>{{ $taskWorkload['completed_today'] }}</dd><dt>مكتملة هذا الأسبوع</dt><dd>{{ $taskWorkload['completed_week'] }}</dd></dl></section>
  @if($deliveryPerformanceSummary || $supportPerformanceSummary || $productModeratorPerformanceSummary || $financePerformanceSummary)
  <section><h2>فترة الأداء العامة</h2><form method="GET"><label>الفترة<select name="performance_period"><option value="today" @selected(request('performance_period') === 'today')>اليوم</option><option value="yesterday" @selected(request('performance_period') === 'yesterday')>أمس</option><option value="week" @selected(!request('performance_period') || request('performance_period') === 'week')>هذا الأسبوع</option><option value="month" @selected(request('performance_period') === 'month')>هذا الشهر</option><option value="custom" @selected(request('performance_period') === 'custom')>فترة مخصصة</option></select></label><label>من<input type="date" name="performance_from" value="{{ request('performance_from') }}"></label><label>إلى<input type="date" name="performance_to" value="{{ request('performance_to') }}"></label><button>تطبيق الفترة</button></form></section>
  @endif
  @if($deliveryPerformanceSummary)
  <form method="GET"><h2>فلاتر أداء التوصيل</h2><label>الفترة<select name="performance_period"><option value="today">اليوم</option><option value="yesterday">أمس</option><option value="week" @selected($deliveryPerformanceSummary['period'] === 'week')>هذا الأسبوع</option><option value="month">هذا الشهر</option><option value="custom">فترة مخصصة</option></select></label><label>من<input type="date" name="performance_from" value="{{ request('performance_from') }}"></label><label>إلى<input type="date" name="performance_to" value="{{ request('performance_to') }}"></label><label>المنطقة<input name="delivery_area" maxlength="120" value="{{ request('delivery_area') }}"></label><label>الحالة<select name="delivery_status"><option value="">الكل</option>@foreach(\App\Enums\DeliveryStatus::cases() as $state)<option value="{{ $state->value }}" @selected(request('delivery_status') === $state->value)>{{ $state->value }}</option>@endforeach</select></label><button>تطبيق الفلاتر</button></form>
  <section><h2>أداء التوصيل</h2><form method="GET"><label>الفترة<select name="performance_period"><option value="today" @selected($deliveryPerformanceSummary['period'] === 'today')>اليوم</option><option value="week" @selected($deliveryPerformanceSummary['period'] === 'week')>هذا الأسبوع</option><option value="month" @selected($deliveryPerformanceSummary['period'] === 'month')>هذا الشهر</option></select></label><button>تطبيق الفترة</button></form><dl><dt>المسندة</dt><dd>{{ $deliveryPerformanceSummary['assigned'] }}</dd><dt>المقبولة</dt><dd>{{ $deliveryPerformanceSummary['accepted'] }}</dd><dt>المسلّمة</dt><dd>{{ $deliveryPerformanceSummary['delivered'] }}</dd><dt>الفاشلة</dt><dd>{{ $deliveryPerformanceSummary['failed'] }}</dd><dt>المرتجعة</dt><dd>{{ $deliveryPerformanceSummary['returned'] }}</dd><dt>الملغاة</dt><dd>{{ $deliveryPerformanceSummary['cancelled'] }}</dd><dt>ضمن الموعد</dt><dd>{{ $deliveryPerformanceSummary['on_time'] }}</dd><dt>متأخرة</dt><dd>{{ $deliveryPerformanceSummary['late'] }}</dd><dt>النشطة</dt><dd>{{ $deliveryPerformanceSummary['active'] }}</dd><dt>متوسط الاستجابة</dt><dd>{{ $deliveryPerformanceSummary['average_response_minutes'] !== null ? $deliveryPerformanceSummary['average_response_minutes'].' دقيقة' : 'غير متاح' }}</dd><dt>متوسط الطريق إلى التاجر</dt><dd>{{ $deliveryPerformanceSummary['average_to_merchant_minutes'] !== null ? $deliveryPerformanceSummary['average_to_merchant_minutes'].' دقيقة' : 'غير متاح' }}</dd><dt>متوسط انتظار التاجر</dt><dd>{{ $deliveryPerformanceSummary['average_merchant_wait_minutes'] !== null ? $deliveryPerformanceSummary['average_merchant_wait_minutes'].' دقيقة' : 'غير متاح' }}</dd><dt>متوسط الطريق إلى العميل</dt><dd>{{ $deliveryPerformanceSummary['average_delivery_travel_minutes'] !== null ? $deliveryPerformanceSummary['average_delivery_travel_minutes'].' دقيقة' : 'غير متاح' }}</dd><dt>متوسط وقت التسليم عند العميل</dt><dd>{{ $deliveryPerformanceSummary['average_doorstep_minutes'] !== null ? $deliveryPerformanceSummary['average_doorstep_minutes'].' دقيقة' : 'غير متاح' }}</dd><dt>متوسط المدة الإجمالية</dt><dd>{{ $deliveryPerformanceSummary['average_total_minutes'] !== null ? $deliveryPerformanceSummary['average_total_minutes'].' دقيقة' : 'غير متاح' }}</dd></dl><p>الالتزام بالموعد يحسب فقط للمهام التي تحمل موعدًا متوقعًا محفوظًا؛ لا تُفبرك نتيجة للمهام التاريخية.</p>
    <p><strong>نسبة التسليم في الوقت:</strong> {{ $deliveryPerformanceSummary['on_time_rate'] !== null ? $deliveryPerformanceSummary['on_time_rate'].'%' : 'غير متاح' }} — <strong>تأخير منسوب للمندوب:</strong> {{ $deliveryPerformanceSummary['worker_responsible_late'] }} — <strong>تأخير غير منسوب للمندوب:</strong> {{ $deliveryPerformanceSummary['external_responsibility_late'] }} — <strong>الإكمال:</strong> {{ $deliveryPerformanceSummary['completion_rate'] !== null ? $deliveryPerformanceSummary['completion_rate'].'%' : 'غير متاح' }} — <strong>تقييم العملاء:</strong> {{ $deliveryPerformanceSummary['average_rating'] !== null ? $deliveryPerformanceSummary['average_rating'].'/5 ('.$deliveryPerformanceSummary['rating_count'].')' : 'غير متاح' }} — <strong>المؤشر الداخلي:</strong> {{ $deliveryPerformanceSummary['score'] !== null ? $deliveryPerformanceSummary['score'].'/100' : 'بيانات غير كافية' }}</p><p>المؤشر تشغيلي للمراجعة البشرية فقط ولا يصدر قرارًا آليًا. التأخير الخارجي لا يخفض مكوّن الالتزام، ولا تدخل دقة الإثبات أو امتثال السياسة حتى تتوفر بيانات موثوقة.</p>
    <div class="table-wrap"><table><thead><tr><th>التوصيل</th><th>الطلب</th><th>موقع الاستلام</th><th>منطقة التسليم</th><th>الإسناد</th><th>القبول</th><th>الاستلام</th><th>التسليم</th><th>المدة الكلية</th><th>الحالة</th><th>التأخير</th><th>سبب التأخير والمسؤولية</th><th>التقييم</th></tr></thead><tbody>@forelse($deliveryPerformanceSummary['history'] as $delivery)<tr><td>#{{ $delivery->id }}</td><td>#{{ $delivery->order_id }}</td><td>{{ $delivery->origin_snapshot['location_name'] ?? 'غير محدد' }}</td><td>{{ collect([$delivery->destination_snapshot['governorate'] ?? null, $delivery->destination_snapshot['city'] ?? null])->filter()->join(' — ') ?: 'غير محددة' }}</td><td>{{ $delivery->assigned_at?->format('Y-m-d H:i') }}</td><td>{{ $delivery->accepted_at?->format('Y-m-d H:i') ?? '—' }}</td><td>{{ $delivery->picked_up_at?->format('Y-m-d H:i') ?? '—' }}</td><td>{{ $delivery->delivered_at?->format('Y-m-d H:i') ?? '—' }}</td><td>{{ $delivery->assigned_at && $delivery->delivered_at ? round($delivery->assigned_at->diffInSeconds($delivery->delivered_at) / 60, 1).' دقيقة' : 'غير مكتملة' }}</td><td>{{ $delivery->status->value }}</td><td>{{ $delivery->delivered_at && $delivery->expected_delivery_at ? ($delivery->delivered_at->gt($delivery->expected_delivery_at) ? round($delivery->expected_delivery_at->diffInSeconds($delivery->delivered_at) / 60, 1).' دقيقة' : 'ضمن الموعد') : 'غير متاح' }}</td><td>{{ $delivery->delay_reason ? $delivery->delay_reason.' — '.($delivery->delay_responsibility ?? 'غير محددة') : 'غير مسجل' }}</td><td>{{ $delivery->rating ? $delivery->rating->rating.'/5' : 'غير متاح' }}</td></tr>@empty<tr><td colspan="13">لا توجد توصيلات في الفترة.</td></tr>@endforelse</tbody></table></div>
  </section>
  @if($comparisonPeers->isNotEmpty())<section><h2>مقارنة داخل القسم ونوع العمل</h2><form method="GET"><input type="hidden" name="performance_period" value="{{ request('performance_period', 'week') }}"><input type="hidden" name="performance_from" value="{{ request('performance_from') }}"><input type="hidden" name="performance_to" value="{{ request('performance_to') }}"><label>الموظف<select name="compare_staff" required><option value="">اختر</option>@foreach($comparisonPeers as $peer)<option value="{{ $peer->id }}" @selected((int) request('compare_staff') === $peer->id)>{{ $peer->name }} — {{ $peer->employee_number }}</option>@endforeach</select></label><button>قارن</button></form>
  @if($performanceComparison)<table><thead><tr><th>المؤشر</th><th>{{ $employee->name }}</th><th>{{ $performanceComparison['peer']->name }}</th></tr></thead><tbody>@foreach($performanceComparison['metrics'] as $key => $label)<tr><th>{{ $label }}</th><td>{{ $performanceComparison['primarySummary'][$key] ?? 'غير متاح' }}</td><td>{{ $performanceComparison['peerSummary'][$key] ?? 'غير متاح' }}</td></tr>@endforeach</tbody></table><p>المقارنة تشغيلية للمراجعة البشرية ولا تنشئ ترتيبًا أو قرارًا آليًا.</p>@endif</section>@endif
  @endif
  @if($supportPerformanceSummary)
  <section><h2>أداء الدعم</h2><form method="GET"><label>الفترة<select name="performance_period"><option value="today" @selected($supportPerformanceSummary['period'] === 'today')>اليوم</option><option value="week" @selected($supportPerformanceSummary['period'] === 'week')>هذا الأسبوع</option><option value="month" @selected($supportPerformanceSummary['period'] === 'month')>هذا الشهر</option></select></label><button>تطبيق الفترة</button></form><dl><dt>التذاكر المسندة</dt><dd>{{ $supportPerformanceSummary['assigned'] }}</dd><dt>التذاكر المعالجة برد عام</dt><dd>{{ $supportPerformanceSummary['handled'] }}</dd><dt>الردود العامة</dt><dd>{{ $supportPerformanceSummary['public_replies'] }}</dd><dt>المحلولة</dt><dd>{{ $supportPerformanceSummary['resolved'] }}</dd><dt>المغلقة</dt><dd>{{ $supportPerformanceSummary['closed'] }}</dd><dt>مرات إعادة الفتح</dt><dd>{{ $supportPerformanceSummary['reopened'] }}</dd><dt>تجاوزات SLA للاستجابة</dt><dd>{{ $supportPerformanceSummary['sla_breaches'] }}</dd><dt>متوسط أول استجابة</dt><dd>{{ $supportPerformanceSummary['average_first_response_minutes'] !== null ? $supportPerformanceSummary['average_first_response_minutes'].' دقيقة' : 'غير متاح' }}</dd><dt>متوسط الحل</dt><dd>{{ $supportPerformanceSummary['average_resolution_minutes'] !== null ? $supportPerformanceSummary['average_resolution_minutes'].' دقيقة' : 'غير متاح' }}</dd><dt>رضا العملاء</dt><dd>غير متاح — لا تُجمع تقييمات بعد</dd></dl><p>لا يوجد مسار محادثات مستقل حاليًا؛ لذلك يعرض المؤشر التذاكر والردود العامة المسجلة فقط.</p>
    <div class="table-wrap"><table><thead><tr><th>التذكرة</th><th>الموضوع</th><th>الحالة</th><th>الإسناد</th><th>أول استجابة</th><th>الحل</th><th>إعادة الفتح</th></tr></thead><tbody>@forelse($supportPerformanceSummary['history'] as $ticket)<tr><td>#{{ $ticket->id }}</td><td>{{ $ticket->topic }}</td><td>{{ $ticket->status->label() }}</td><td>{{ $ticket->assigned_at?->format('Y-m-d H:i') ?? '—' }}</td><td>{{ $ticket->first_response_at?->format('Y-m-d H:i') ?? '—' }}</td><td>{{ $ticket->resolved_at?->format('Y-m-d H:i') ?? '—' }}</td><td>{{ $ticket->reopened_count }}</td></tr>@empty<tr><td colspan="7">لا توجد تذاكر دعم في الفترة.</td></tr>@endforelse</tbody></table></div>
  </section>
  @endif
  @if($productModeratorPerformanceSummary)
  <section><h2>أداء مراجعة الكتالوج</h2><form method="GET"><label>الفترة<select name="performance_period"><option value="today" @selected($productModeratorPerformanceSummary['period'] === 'today')>اليوم</option><option value="week" @selected($productModeratorPerformanceSummary['period'] === 'week')>هذا الأسبوع</option><option value="month" @selected($productModeratorPerformanceSummary['period'] === 'month')>هذا الشهر</option></select></label><button>تطبيق الفترة</button></form><dl><dt>إجمالي المراجعات</dt><dd>{{ $productModeratorPerformanceSummary['reviewed'] }}</dd><dt>الموافق عليها</dt><dd>{{ $productModeratorPerformanceSummary['approved'] }}</dd><dt>المرفوضة</dt><dd>{{ $productModeratorPerformanceSummary['rejected'] }}</dd><dt>طلبات التعديل</dt><dd>{{ $productModeratorPerformanceSummary['changes_requested'] }}</dd><dt>متوسط زمن المراجعة</dt><dd>{{ $productModeratorPerformanceSummary['average_review_minutes'] !== null ? $productModeratorPerformanceSummary['average_review_minutes'].' دقيقة' : 'غير متاح' }}</dd><dt>عبء الانتظار الحالي</dt><dd>{{ $productModeratorPerformanceSummary['pending_workload'] }}</dd><dt>القرارات المعكوسة</dt><dd>{{ $productModeratorPerformanceSummary['reversed_decisions'] }}</dd></dl><p>السرعة مؤشر تشغيلي فقط، ولا تُستخدم وحدها لتقييم جودة المراجع.</p></section>
  @endif
  @if($financePerformanceSummary)
  <section><h2>أداء مراجعة الدفعات</h2><form method="GET"><label>الفترة<select name="performance_period"><option value="today" @selected($financePerformanceSummary['period'] === 'today')>اليوم</option><option value="week" @selected($financePerformanceSummary['period'] === 'week')>هذا الأسبوع</option><option value="month" @selected($financePerformanceSummary['period'] === 'month')>هذا الشهر</option></select></label><button>تطبيق الفترة</button></form><dl><dt>الدفعات المراجعة</dt><dd>{{ $financePerformanceSummary['reviewed'] }}</dd><dt>المقبولة</dt><dd>{{ $financePerformanceSummary['accepted'] }}</dd><dt>المرفوضة</dt><dd>{{ $financePerformanceSummary['rejected'] }}</dd><dt>المصعّدة كمشبوهة</dt><dd>{{ $financePerformanceSummary['escalated'] }}</dd><dt>حالات تحتاج تصحيح مبلغ</dt><dd>{{ $financePerformanceSummary['corrections'] }}</dd><dt>فروقات المطابقة</dt><dd>{{ $financePerformanceSummary['reconciliation_discrepancies'] }}</dd><dt>متوسط زمن المراجعة</dt><dd>{{ $financePerformanceSummary['average_review_minutes'] !== null ? $financePerformanceSummary['average_review_minutes'].' دقيقة' : 'غير متاح' }}</dd><dt>عبء الانتظار الحالي</dt><dd>{{ $financePerformanceSummary['pending_workload'] }}</dd></dl><p>زمن المراجعة مؤشر تشغيلي فقط؛ صحة المبلغ والطلب والإثبات لها الأولوية ولا يُكافأ القبول السريع.</p></section>
  @endif
  @if($employee->account_status === \App\Enums\AccountStatus::Active)
  <section><h2>إسناد مهمة جديدة</h2><form method="POST" action="{{ route('admin.staff.tasks.store', $employee) }}">@csrf<label>العنوان<input name="title" minlength="3" maxlength="160" required></label><label>الوصف<textarea name="description" maxlength="5000"></textarea></label><label>نوع المهمة<select name="task_type" required><option value="general">عامة</option><option value="order">طلب</option><option value="merchant">تاجر</option><option value="product">منتج</option><option value="payment">دفعة</option><option value="withdrawal">سحب</option><option value="complaint">شكوى</option><option value="delivery">توصيل</option><option value="support">دعم</option></select></label><label>رقم السجل المرتبط — اختياري<input type="number" name="related_id" min="1"><small>يُتحقق منه داخل نوع المهمة المختار. اتركه فارغًا للمهمة العامة.</small></label><label>الأولوية<select name="priority" required>@foreach($taskPriorities as $priority)<option value="{{ $priority->value }}" @selected($priority === \App\Enums\StaffTaskPriority::Normal)>{{ $priority->label() }}</option>@endforeach</select></label><label>موعد الاستحقاق (UTC)<input type="datetime-local" name="due_at"></label><label>ملاحظات داخلية<textarea name="notes" maxlength="5000"></textarea></label><label>سبب الإسناد<textarea name="reason" minlength="5" maxlength="500" required></textarea></label><label>كلمة مرور حسابك<input type="password" name="current_password" autocomplete="current-password" required></label><button>إنشاء وإسناد المهمة</button></form></section>
  @endif
  <section><h2>المهام</h2><p>آخر 50 مهمة مسندة لهذا الموظف. المهام المكتملة والملغاة محفوظة للقراءة ولا يعاد فتحها من هذا المسار.</p>
    @forelse($staffTasks as $task)
      <article class="staff-task"><h3>#{{ $task->id }} — {{ $task->title }}</h3><dl><dt>النوع</dt><dd>{{ $task->task_type }}</dd><dt>السجل المرتبط</dt><dd>{{ $task->related_id ? '#'.$task->related_id : 'لا يوجد' }}</dd><dt>الحالة</dt><dd>{{ $task->status->label() }}</dd><dt>الأولوية</dt><dd>{{ $task->priority->label() }}</dd><dt>الموعد (UTC)</dt><dd>{{ $task->due_at?->format('Y-m-d H:i') ?? 'بدون موعد' }}</dd><dt>أسندها</dt><dd>{{ $task->assigner?->name ?? 'حساب سابق' }}</dd></dl>@if($task->description)<p>{{ $task->description }}</p>@endif @if($task->notes)<p><strong>ملاحظة داخلية:</strong> {{ $task->notes }}</p>@endif
      @if(!in_array($task->status, [\App\Enums\StaffTaskStatus::Completed, \App\Enums\StaffTaskStatus::Cancelled], true))
        <form method="POST" action="{{ route('admin.staff.tasks.update', $task) }}">@csrf @method('PATCH')<input type="hidden" name="expected_version" value="{{ $task->version }}"><label>الموظف المسند إليه<select name="assigned_to" required>@foreach($taskAssignees as $assignee)<option value="{{ $assignee->id }}" @selected($task->assigned_to === $assignee->id)>{{ $assignee->name }} — {{ $assignee->employee_number }}</option>@endforeach</select></label><label>الأولوية<select name="priority" required>@foreach($taskPriorities as $priority)<option value="{{ $priority->value }}" @selected($task->priority === $priority)>{{ $priority->label() }}</option>@endforeach</select></label><label>الحالة<select name="status" required>@foreach($taskStatuses as $status)<option value="{{ $status->value }}" @selected($task->status === $status)>{{ $status->label() }}</option>@endforeach</select></label><label>موعد الاستحقاق (UTC)<input type="datetime-local" name="due_at" value="{{ $task->due_at?->format('Y-m-d\TH:i') }}"></label><label>سبب التغيير<textarea name="reason" minlength="5" maxlength="500" required></textarea></label><label>كلمة مرور حسابك<input type="password" name="current_password" autocomplete="current-password" required></label><button>حفظ المهمة</button></form>
      @endif
      </article>
    @empty<p>لا توجد مهام مسندة لهذا الموظف.</p>@endforelse
  </section>
  @if($employee->id !== auth()->id())
    @if($employee->account_status === \App\Enums\AccountStatus::Invited)
      <section><h2>إعادة إرسال الدعوة</h2><p>يبطل أي رابط سابق ويرسل رابطًا جديدًا أحادي الاستخدام.</p><form method="POST" action="{{ route('admin.staff.invitation.resend', $employee) }}">@csrf<label>سبب إعادة الإرسال<textarea name="reason" minlength="5" maxlength="500" required>{{ old('reason') }}</textarea></label><label>كلمة مرور حسابك<input type="password" name="current_password" autocomplete="current-password" required></label><button>إبطال الرابط السابق وإرسال دعوة جديدة</button></form></section>
    @endif
    @if($employee->account_status !== \App\Enums\AccountStatus::Terminated)
      <section><h2>ملخص ما قبل إنهاء الخدمة</h2><dl><dt>الموظف</dt><dd>{{ $employee->name }} — {{ $employee->employee_number }}</dd><dt>المهام النشطة</dt><dd>{{ $terminationSummary['active_tasks'] }}</dd><dt>المحادثات/التذاكر النشطة</dt><dd>{{ $terminationSummary['active_chats'] }}</dd><dt>التوصيلات المسندة النشطة</dt><dd>{{ $terminationSummary['active_deliveries'] }}</dd><dt>دور أو صلاحيات حساسة</dt><dd>{{ $terminationSummary['sensitive_role'] ? 'نعم — تتطلب مراجعة إضافية' : 'لا' }}</dd><dt>الجلسات الحالية</dt><dd>{{ $terminationSummary['active_sessions'] ?? 'غير متاح' }}</dd></dl></section>
    <section><h2>تعديل الأدوار التشغيلية</h2><p>أدوار العميل والتاجر—إن وجدت—تبقى محفوظة. تغيير الأدوار ينهي جلسات الموظف ويطبق الصلاحيات الجديدة فورًا.</p><form method="POST" action="{{ route('admin.staff.roles.update', $employee) }}">@csrf @method('PATCH')<fieldset><legend>الأدوار</legend>@foreach($manageableRoles as $role)<label><input type="checkbox" name="role_ids[]" value="{{ $role->id }}" @checked($employee->roles->contains('id', $role->id))> {{ $role->name }} <code>{{ $role->slug }}</code></label>@endforeach</fieldset><label>سبب التغيير<textarea name="reason" minlength="5" maxlength="500" required>{{ old('reason') }}</textarea></label><label>كلمة مرور حسابك<input type="password" name="current_password" autocomplete="current-password" required></label><button>حفظ الأدوار</button></form></section>
    <section><h2>الصلاحيات المباشرة الإضافية</h2><p>هذه إضافات فوق صلاحيات الأدوار ولا تلغيها. أي تغيير ينهي جلسات الموظف.</p><form method="POST" action="{{ route('admin.staff.permissions.update', $employee) }}">@csrf @method('PATCH')<fieldset><legend>الصلاحيات</legend>@foreach($availablePermissions as $permission)<label><input type="checkbox" name="permission_ids[]" value="{{ $permission->id }}" @checked($employee->directPermissions->contains('id', $permission->id))> {{ $permission->name }} <code>{{ $permission->slug }}</code></label>@endforeach</fieldset><label>سبب التغيير<textarea name="reason" minlength="5" maxlength="500" required>{{ old('reason') }}</textarea></label><label>كلمة مرور حسابك<input type="password" name="current_password" autocomplete="current-password" required></label><button>حفظ الصلاحيات المباشرة</button></form></section>
    @endif
    @if(in_array($employee->account_status, [\App\Enums\AccountStatus::Active, \App\Enums\AccountStatus::OnLeave, \App\Enums\AccountStatus::Suspended], true))
      <section><h2>{{ $employee->account_status === \App\Enums\AccountStatus::Active ? 'تغيير توفر الحساب' : 'إعادة تفعيل الحساب' }}</h2><p>{{ $employee->account_status === \App\Enums\AccountStatus::Active ? 'الإجازة أو التعليق يمنعان الدخول فورًا وينهيان الجلسات الحالية.' : 'إعادة التفعيل تسمح بالدخول مجددًا ولا تنشئ جلسة تلقائيًا.' }}</p><form method="POST" action="{{ route('admin.staff.status.update', $employee) }}">@csrf @method('PATCH') @if($employee->account_status === \App\Enums\AccountStatus::Active)<label>الحالة الجديدة<select name="status" required><option value="on_leave">في إجازة</option><option value="suspended">معلّق</option></select></label>@else<input type="hidden" name="status" value="active">@endif<label>سبب الإجراء<textarea name="reason" minlength="5" maxlength="500" required>{{ old('reason') }}</textarea></label><label>كلمة مرور حسابك<input type="password" name="current_password" autocomplete="current-password" required></label><button>{{ $employee->account_status === \App\Enums\AccountStatus::Active ? 'حفظ الحالة وقطع الجلسات' : 'إعادة تفعيل الحساب' }}</button></form></section>
    @endif
    <section><h2>إنهاء كل الجلسات</h2><p>يُنهي جلسات هذا الموظف ويدوّر رمز تذكر الدخول، ولا يغيّر أدواره أو صلاحياته.</p><form method="POST" action="{{ route('admin.staff.sessions.revoke', $employee) }}">@csrf<label>سبب الإجراء<textarea name="reason" minlength="5" maxlength="500" required>{{ old('reason') }}</textarea></label><label>كلمة مرور حسابك<input type="password" name="current_password" autocomplete="current-password" required></label><button>إنهاء كل الجلسات</button></form></section>
    @if($employee->account_status !== \App\Enums\AccountStatus::Terminated)
      <section><h2>إنهاء خدمة الموظف</h2><p>اختر وجهة مستقلة لكل عمل متبقٍ. التوصيل المقبول أو الجاري لا يعود للطابور ويجب نقله إلى مندوب محدد.</p><form method="POST" action="{{ route('admin.staff.terminate', $employee) }}">@csrf
      <label>وجهة المهام<select name="tasks_destination"><option value="specific">موظف محدد</option><option value="department">طابور القسم</option><option value="unassigned">غير مسند</option></select></label><label>بديل المهام<select name="reassign_tasks_to"><option value="">اختر عند استخدام موظف محدد</option>@foreach($taskAssignees->where('id', '!=', $employee->id) as $assignee)<option value="{{ $assignee->id }}">{{ $assignee->name }} — {{ $assignee->employee_number }}</option>@endforeach</select></label>
      <label>وجهة المحادثات<select name="chats_destination"><option value="specific">موظف محدد</option><option value="department">طابور القسم</option><option value="unassigned">غير مسند</option></select></label><label>بديل المحادثات<select name="reassign_chats_to"><option value="">اختر موظف دعم</option>@foreach($taskAssignees->where('id', '!=', $employee->id) as $assignee)<option value="{{ $assignee->id }}">{{ $assignee->name }} — {{ $assignee->employee_number }}</option>@endforeach</select></label>
      <label>وجهة التوصيلات<select name="deliveries_destination"><option value="specific">مندوب محدد</option><option value="department">طابور القسم</option><option value="unassigned">غير مسند</option></select></label><label>بديل التوصيلات<select name="reassign_deliveries_to"><option value="">اختر مندوب توصيل</option>@foreach($taskAssignees->where('id', '!=', $employee->id) as $assignee)<option value="{{ $assignee->id }}">{{ $assignee->name }} — {{ $assignee->employee_number }}</option>@endforeach</select></label>
      <label>اكتب بريد الموظف للتأكيد<input type="email" name="confirmation" autocomplete="off" required></label><label>سبب إنهاء الخدمة<textarea name="reason" minlength="5" maxlength="500" required>{{ old('reason') }}</textarea></label><label>كلمة مرور حسابك<input type="password" name="current_password" autocomplete="current-password" required></label><button>إعادة التوزيع وإنهاء الخدمة مع حفظ التاريخ</button></form></section>
    @endif
  @endif
  <section><h2>سجل الأمان</h2><p>آخر 50 إجراء متعلقًا بحالة الحساب والجلسات. لا تُعرض بيانات الجهاز أو عنوان IP.</p><div class="table-wrap"><table><thead><tr><th>الوقت</th><th>الإجراء</th><th>نفّذه</th><th>السبب</th></tr></thead><tbody>
    @forelse($securityEvents as $event)<tr><td>{{ $event->created_at?->format('Y-m-d H:i:s') }} UTC</td><td>{{ match($event->action) { 'staff.invited' => 'إنشاء الدعوة', 'staff.invitation_resent' => 'إعادة إرسال الدعوة', 'staff.invitation_delivery_failed' => 'فشل إرسال الدعوة', 'staff.invitation_accepted' => 'قبول الدعوة', 'staff.terminated' => 'إنهاء الخدمة', 'staff.account_status_changed' => 'تغيير حالة الحساب', 'staff.operational_roles_changed' => 'تغيير الأدوار التشغيلية', 'staff.direct_permissions_changed' => 'تغيير الصلاحيات المباشرة', 'staff.profile_updated' => 'تحديث الهوية الوظيفية', 'staff.email_changed' => 'تغيير البريد', 'staff.scope_schedule_updated' => 'تحديث النطاق والدوام', default => 'إنهاء الجلسات' } }}</td><td>{{ $event->actor?->name ?? 'النظام' }}</td><td>{{ $event->reason ?: 'غير مذكور' }}</td></tr>
    @empty<tr><td colspan="4">لا توجد إجراءات أمنية مسجلة لهذا الموظف.</td></tr>@endforelse
  </tbody></table></div></section>
  <section><h2>تاريخ الصلاحيات والتنظيم</h2><p>آخر 50 تغييرًا في الدور أو الصلاحيات أو القسم أو الحالة، بعد تحويله إلى ملخص آمن.</p><div class="table-wrap"><table><thead><tr><th>الوقت</th><th>التغيير</th><th>نفّذه</th><th>السبب</th></tr></thead><tbody>
    @forelse($permissionHistory as $event)<tr><td>{{ $event['created_at']?->format('Y-m-d H:i:s') }} UTC</td><td><ul>@foreach($event['summary'] as $change)<li>{{ $change }}</li>@endforeach</ul></td><td>{{ $event['actor_name'] }}</td><td>{{ $event['reason'] ?: 'غير مذكور' }}</td></tr>
    @empty<tr><td colspan="4">لا يوجد تاريخ صلاحيات أو تنظيم بعد.</td></tr>@endforelse
  </tbody></table></div></section>
  <section><h2>خط نشاط الموظف</h2><p>آخر 50 إجراء تشغيلي سجله النظام لهذا الموظف كمنفذ. لا تُحمّل حقول before/after أو metadata أو معلومات الجهاز.</p><div class="table-wrap"><table><thead><tr><th>الوقت</th><th>الإجراء</th><th>مرجع السجل</th></tr></thead><tbody>
    @forelse($activityEvents as $event)<tr><td>{{ $event->created_at?->format('Y-m-d H:i:s') }} UTC</td><td><code>{{ $event->action }}</code></td><td>{{ $event->subject_id ? '#'.$event->subject_id : 'بدون مرجع' }}</td></tr>
    @empty<tr><td colspan="3">لا توجد أحداث تشغيلية مسجلة لهذا الموظف.</td></tr>@endforelse
  </tbody></table></div></section>
  @if($canViewStaffNotes)
  <section><h2>ملاحظات الموظف الداخلية</h2><p>آخر 50 ملاحظة. الملاحظات سجل تراكمي لا يُعدّل ولا يُحذف.</p>
    @if($canManageStaffNotes)<form method="POST" action="{{ route('admin.staff.notes.store', $employee) }}">@csrf<label>ملاحظة جديدة<textarea name="body" minlength="3" maxlength="2000" required></textarea></label><label>كلمة مرور حسابك<input type="password" name="current_password" autocomplete="current-password" required></label><button>إضافة الملاحظة</button></form>@endif
    @forelse($staffNotes as $note)<article class="staff-task"><p>{{ $note->body }}</p><small>{{ $note->author?->name ?? 'حساب سابق' }} — {{ $note->created_at?->format('Y-m-d H:i:s') }} UTC</small></article>
    @empty<p>لا توجد ملاحظات داخلية.</p>@endforelse
  </section>
  @endif
  <section><h2>الصلاحيات الفعلية</h2><p>المصدر يوضح الدور الذي منح كل صلاحية.</p>
    <div class="table-wrap"><table><thead><tr><th>المجموعة</th><th>الصلاحية</th><th>المعرّف</th><th>المصدر</th></tr></thead><tbody>
      @forelse($effectivePermissions as $permission)<tr><td>{{ $permission['group'] ?: 'عام' }}</td><td>{{ $permission['name'] }}</td><td><code>{{ $permission['slug'] }}</code></td><td>{{ $permission['sources']->join('، ') }}</td></tr>
      @empty<tr><td colspan="4">لا توجد صلاحيات فعلية لهذا الدور.</td></tr>@endforelse
    </tbody></table></div>
  </section>
</div>
@endsection
@push('styles')
<style>
main{max-width:1100px}.staff-detail{max-width:1060px;margin:0 auto}.staff-detail dl{display:grid;grid-template-columns:150px 1fr;gap:8px 16px}.staff-detail dt{font-weight:700}.staff-detail dd{margin:0}.chips{display:flex;gap:8px;flex-wrap:wrap}.chips span{background:#eaf1fb;border-radius:999px;padding:4px 11px}.staff-task{border:1px solid #dce2ea;border-radius:10px;padding:14px;margin:12px 0}.staff-task h3{margin-top:0}.schedule-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px}.schedule-grid fieldset{min-width:0}.table-wrap{overflow:auto;border:1px solid #dce2ea;border-radius:10px}table{width:100%;border-collapse:collapse;min-width:700px}th,td{text-align:right;padding:10px;border-bottom:1px solid #e7ebf0}@media(max-width:520px){.staff-detail dl{grid-template-columns:1fr}.staff-detail dd{margin-bottom:8px}}
</style>
@endpush
